# Generated by Django 4.2.7 on 2023-11-17 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL')),
                ('av', models.ImageField(null=True, upload_to='user-images/', verbose_name='Аватарка профілю')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Власник профіля')),
            ],
            options={
                'verbose_name': 'Профіль',
                'verbose_name_plural': 'Профіля',
            },
        ),
    ]
