# Generated by Django 4.2.7 on 2023-11-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_av'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='av',
            field=models.ImageField(null=True, upload_to='user-images/', verbose_name='Аватарка профілю'),
        ),
    ]
