# Generated by Django 4.2.7 on 2023-11-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Назва продукта')),
                ('image', models.ImageField(null=True, upload_to='product-img/', verbose_name='Фото подукта')),
                ('about', models.TextField(max_length=500, null=True, verbose_name='Про продукт')),
                ('price', models.IntegerField(null=True, verbose_name='Ціна')),
                ('in_stock', models.BooleanField(default=True, null=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
    ]
